name: Deploy Docker Compose Stack to Production

env:
  SERVICE_DIRECTORY: ~/docker/chirpstack

on:
  push:
    branches:
      - production
    paths:
      - 'compose.yml'
      - 'configuration/**'
      - 'ansible/**'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/production' && 'production' || 'staging' }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOYMENT_USER_PRIVATE_KEY }}

      - name: Add host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.HOST_KEY }}" >> ~/.ssh/known_hosts

      - name: Run Ansible Playbook
        env:
          # Disables dynamic host key prompting, though known_hosts already covers this
          ANSIBLE_HOST_KEY_CHECKING: "false"
        run: |
          ansible-playbook ansible/deploy.yml \
            -i "${{ secrets.HOST_IP }}," \
            -u "${{ secrets.DEPLOYMENT_USER }}" \
            -e "service_dir=${{ env.SERVICE_DIRECTORY }}" \
            -e "host_domain=${{ secrets.HOST_DOMAIN }}" \
            -e "chirpstack_uid=${{ secrets.CHIRPSTACK_UID }}" \
            -e "chirpstack_gid=${{ secrets.CHIRPSTACK_GID }}" \
            -e "chirpstack_api_secret=${{ secrets.CHIRPSTACK_API_SECRET }}" \
            -e "postgres_user=${{ secrets.POSTGRES_USER }}" \
            -e "postgres_password=${{ secrets.POSTGRES_PASSWORD }}" \
            -e "postgres_db=${{ secrets.POSTGRES_DB }}" \
            -e "mosquitto_username=${{ secrets.MOSQUITTO_INTERNAL_USERNAME }}" \
            -e "mosquitto_password=${{ secrets.MOSQUITTO_INTERNAL_PASSWORD }}" \
            -e "mosquitto_password_hash=${{ secrets.MOSQUITTO_INTERNAL_PASSWORD_HASH }}" \
            -e "traefik_acme_email=${{ secrets.TRAEFIK_ACME_EMAIL }}"
            